apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraping-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraping
  template:
    metadata:
      labels:
        app: scraping
    spec:
      containers:
        - name: scraping
          image: device_certificate_automation_app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: EMAIL
              valueFrom:
                secretKeyRef:
                  name: csp-secret
                  key: email
            - name: PASSWD
              valueFrom:
                secretKeyRef:
                  name: csp-secret
                  key: password
        - name: selenium
          image: selenium/standalone-chrome:latest
          ports:
            - containerPort: 4444
