apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx # このlabelはdeployment自体のlabel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx # deploymentが管理するpodのlabel、基本的には下のtemplateと一緒
  template:
    metadata:
      labels:
        app: nginx # ここのlabelはこのdeploymentによって作成されたpodに付けられているlabel
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
